Importing the basic libraries for implementation of neural networks.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import matplotlib as mpl

Perceptron

Designing

In [2]:
d_set= pd.read_csv('./../Data/addition_dataset_2.csv')
d_set.head()
dset_features=d_set.copy()
dset_labels=dset_features.pop('result')
dset_features=np.array(dset_features)
dset_model_Perceptron = tf.keras.Sequential([
  layers.Dense(1)
])

dset_model_Perceptron.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

Training

In [3]:
dset_model_Perceptron.fit(dset_features, dset_labels, epochs=50,validation_split=0.2)

Epoch 1/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 681us/step - accuracy: 0.0000e+00 - loss: 350533920.0000 - val_accuracy: 0.0000e+00 - val_loss: 608271168.0000
Epoch 2/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - accuracy: 0.0000e+00 - loss: 120116080.0000 - val_accuracy: 0.0000e+00 - val_loss: 166104208.0000
Epoch 3/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - accuracy: 2.7539e-05 - loss: 31193032.0000 - val_accuracy: 0.0000e+00 - val_loss: 29711542.0000
Epoch 4/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step - accuracy: 8.9453e-06 - loss: 5138413.5000 - val_accuracy: 0.0000e+00 - val_loss: 2926171.0000
Epoch 5/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 6.7295e-05 - loss: 441108.1250 - val_accuracy: 0.0000e+00 - val_loss: 131091.7656
Epoch 6/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 3.4522e-06 - loss: 17354.0273 - val_accuracy: 0.0000e+00 - val_loss: 2161.1516
Epoch 7/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 6.2757e-06 - loss: 245.1099 - v

Testing

In [4]:
dset_model_Perceptron.predict(dset_features[:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[ 1.034064 ],
       [ 3.0340316],
       [ 5.0339994],
       [ 7.033967 ],
       [ 9.033935 ],
       [11.033901 ],
       [13.03387  ],
       [15.033837 ],
       [17.033804 ],
       [19.033772 ],
       [21.03374  ],
       [23.033709 ],
       [25.033676 ],
       [27.033642 ],
       [29.03361  ],
       [31.033577 ],
       [33.033546 ],
       [35.033516 ],
       [37.03348  ],
       [39.03345  ]], dtype=float32)

Multi layered Perceptron / Feed Forward Neural Network

Designing

In [5]:
dset_model_MultiLayerPerceptron = tf.keras.Sequential([
    layers.Dense(64, activation='linear', input_shape=(dset_features.shape[1],)),  # Hidden layer 1
    layers.Dense(32, activation='selu'),  # Hidden layer 2
    layers.Dense(1, activation='linear')  # Output layer
])


dset_model_MultiLayerPerceptron.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

c:\Users\akars\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training

In [6]:
dset_model_MultiLayerPerceptron.fit(dset_features, dset_labels, epochs=30,validation_split=0.2)

Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 835us/step - accuracy: 5.4149e-05 - loss: 47299644.0000 - val_accuracy: 0.0000e+00 - val_loss: 5.9694
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - accuracy: 2.9504e-05 - loss: 3.2245 - val_accuracy: 0.0000e+00 - val_loss: 7.2852
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 2.4335e-05 - loss: 3.1875 - val_accuracy: 0.0000e+00 - val_loss: 3.9175
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 1.0890e-04 - loss: 3.1935 - val_accuracy: 0.0000e+00 - val_loss: 4.7257
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 1.2890e-04 - loss: 3.1428 - val_accuracy: 0.0000e+00 - val_loss: 6.0673
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 7.7615e-05 - loss: 3.0639 - val_accuracy: 0.0000e+00 - val_loss: 6.1638
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - accuracy: 1.0962e-04 - loss: 3.0108 - val_accuracy: 0.0000e+00 - val_loss: 4.2391
Epoch 8/30
500/500 ━━━━━━━━

Testing

In [7]:
dset_model_MultiLayerPerceptron.predict(dset_features[:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[ 0.98607063],
       [ 3.035985  ],
       [ 5.0019226 ],
       [ 6.9614844 ],
       [ 9.000017  ],
       [11.042909  ],
       [13.023591  ],
       [15.004663  ],
       [17.000513  ],
       [19.003408  ],
       [21.008821  ],
       [23.014183  ],
       [25.0181    ],
       [27.009024  ],
       [28.999527  ],
       [30.993029  ],
       [32.98878   ],
       [34.986233  ],
       [36.984974  ],
       [38.984684  ]], dtype=float32)

Convolutional Neural Network

Designing

In [8]:
dset_model_Convolutional = tf.keras.Sequential([
    layers.Conv1D(32, kernel_size=2, activation='relu', input_shape=(2, 1)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='linear')
])
dset_model_Convolutional.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


c:\Users\akars\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Training

In [9]:
dset_model_Convolutional.fit(dset_features, dset_labels, epochs=20, validation_split=0.2)

Epoch 1/20


500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 79393888.0000 - mae: 4688.9287 - val_loss: 0.3089 - val_mae: 0.5492
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - loss: 0.2842 - mae: 0.3554 - val_loss: 0.2725 - val_mae: 0.5154
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 0.1744 - mae: 0.3281 - val_loss: 0.2730 - val_mae: 0.5159
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 0.1504 - mae: 0.3225 - val_loss: 0.3266 - val_mae: 0.5649
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 972us/step - loss: 0.1494 - mae: 0.3227 - val_loss: 0.4828 - val_mae: 0.6885
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - loss: 0.8239 - mae: 0.3918 - val_loss: 0.3109 - val_mae: 0.5512
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 0.1490 - mae: 0.3222 - val_loss: 0.3498 - val_mae: 0.5850
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 0.1450 - mae: 0.3173 - val_loss: 0.3762 - val_mae: 0.6071
Epoch 9/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 

Testing

In [10]:
dset_model_Convolutional.predict(dset_features[:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[ 0.75783193],
       [ 2.8495936 ],
       [ 5.020532  ],
       [ 7.1597867 ],
       [ 9.27332   ],
       [11.340355  ],
       [13.387315  ],
       [15.405082  ],
       [17.420677  ],
       [19.422428  ],
       [21.42418   ],
       [23.42593   ],
       [25.427685  ],
       [27.429438  ],
       [29.43119   ],
       [31.432941  ],
       [33.434692  ],
       [35.436447  ],
       [37.43768   ],
       [39.437634  ]], dtype=float32)

LSTM

Designing

In [11]:
dset_model_LSTM = tf.keras.Sequential([
    layers.LSTM(32, activation='relu', input_shape=(2, 1)),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='linear')  # Output layer with linear activation for regression
])

# Compile the model with Mean Squared Error loss
dset_model_LSTM.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])  # Use mean absolute error (mae) as a metric if needed


c:\Users\akars\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Training

In [12]:
dset_model_LSTM.fit(dset_features, dset_labels, epochs=50, validation_split=0.2)


Epoch 1/50


500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 153019808.0000 - mae: 7869.6450 - val_loss: 1.6171 - val_mae: 1.2570
Epoch 2/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - loss: 0.8384 - mae: 0.7402 - val_loss: 1.5789 - val_mae: 1.2419
Epoch 3/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 0.6646 - mae: 0.6861 - val_loss: 1.6683 - val_mae: 1.2770
Epoch 4/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 0.6510 - mae: 0.6822 - val_loss: 1.1190 - val_mae: 1.0428
Epoch 5/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - loss: 0.6266 - mae: 0.6649 - val_loss: 1.9879 - val_mae: 1.3956
Epoch 6/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 992us/step - loss: 0.6280 - mae: 0.6636 - val_loss: 1.1316 - val_mae: 1.0488
Epoch 7/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - loss: 0.5969 - mae: 0.6459 - val_loss: 1.9678 - val_mae: 1.3886
Epoch 8/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - loss: 0.6083 - mae: 0.6542 - val_loss: 1.4025 - val_mae: 1.1699
Epoch 9/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s

Testing

In [13]:
dset_model_LSTM.predict(dset_features[:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step


array([[ 1.0093979],
       [ 3.0404499],
       [ 4.9764657],
       [ 6.993775 ],
       [ 9.001059 ],
       [10.992594 ],
       [12.979063 ],
       [14.969446 ],
       [16.9674   ],
       [18.972647 ],
       [20.983027 ],
       [22.995966 ],
       [25.009237 ],
       [27.021204 ],
       [29.030848 ],
       [31.037672 ],
       [33.041565 ],
       [35.042686 ],
       [37.041363 ],
       [39.038033 ]], dtype=float32)

 
.



























 .

TestOuts

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load the dataset
d_set = pd.read_csv('./../Data/addition_dataset.csv')
dset_features = d_set['equation'].values
dset_labels = d_set['result'].values

# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(dset_features)
word_index = tokenizer.word_index

# Convert text to sequences and pad them
sequences = tokenizer.texts_to_sequences(dset_features)
padded_sequences = pad_sequences(sequences)

# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(word_index) + 1, output_dim=16, input_length=padded_sequences.shape[1]),
    #tf.keras.layers.Flatten(),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Convert labels to NumPy array
dset_labels = tf.convert_to_tensor(dset_labels, dtype=tf.float32)

# Train the model
model.fit(padded_sequences, dset_labels, epochs=200,validation_split=0.2)

# Test the model with new data
test_texts = ["23+24", "27+28"]
test_sequences = tokenizer.texts_to_sequences(test_texts)
padded_test_sequences = pad_sequences(test_sequences, maxlen=padded_sequences.shape[1])
predictions = model.predict(padded_test_sequences)

# Print the predictions
for text, prediction in zip(test_texts, predictions):
    print(f"Text: {text}, Prediction: {prediction[0]}")


In [ ]:

model.predict(pad_sequences(tokenizer.texts_to_sequences("123+1"), maxlen=padded_sequences.shape[1]))