Importing the basic libraries for implementation of neural networks.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import matplotlib as mpl

Perceptron

Designing

In [2]:
d_set= pd.read_csv('./../Data/addition_dataset_2.csv')
d_set.head()
dset_features=d_set.copy()
dset_labels=dset_features.pop('result')
dset_features=np.array(dset_features)
dset_model_Perceptron = tf.keras.Sequential([
  layers.Dense(1)
])

dset_model_Perceptron.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

Training

In [3]:
dset_model_Perceptron.fit(dset_features, dset_labels, epochs=50,validation_split=0.2)

Epoch 1/50
500/500 [==============================] - 1s 1ms/step - loss: 1239337472.0000 - accuracy: 0.0000e+00 - val_loss: 3640441600.0000 - val_accuracy: 0.0000e+00
Epoch 2/50
500/500 [==============================] - 0s 884us/step - loss: 734437184.0000 - accuracy: 0.0000e+00 - val_loss: 2065890688.0000 - val_accuracy: 0.0000e+00
Epoch 3/50
500/500 [==============================] - 0s 907us/step - loss: 400027456.0000 - accuracy: 6.2500e-05 - val_loss: 1062412544.0000 - val_accuracy: 0.0000e+00
Epoch 4/50
500/500 [==============================] - 0s 954us/step - loss: 194782800.0000 - accuracy: 6.2500e-05 - val_loss: 478739936.0000 - val_accuracy: 0.0000e+00
Epoch 5/50
500/500 [==============================] - 0s 997us/step - loss: 81383880.0000 - accuracy: 6.2500e-05 - val_loss: 178927968.0000 - val_accuracy: 0.0000e+00
Epoch 6/50
500/500 [==============================] - 0s 963us/step - loss: 27601048.0000 - accuracy: 6.2500e-05 - val_loss: 51928732.0000 - val_accuracy: 0.00

Testing

In [4]:
dset_model_Perceptron.predict(dset_features[:20])

1/1 [==============================] - 0s 45ms/step


array([[ 1.3895364],
       [ 3.3894947],
       [ 5.3894525],
       [ 7.3894105],
       [ 9.38937  ],
       [11.389328 ],
       [13.389286 ],
       [15.389244 ],
       [17.389202 ],
       [19.38916  ],
       [21.389118 ],
       [23.389076 ],
       [25.389034 ],
       [27.388992 ],
       [29.388952 ],
       [31.388908 ],
       [33.38887  ],
       [35.38883  ],
       [37.388786 ],
       [39.38874  ]], dtype=float32)

Multi layered Perceptron / Feed Forward Neural Network

Designing

In [5]:
dset_model_MultiLayerPerceptron = tf.keras.Sequential([
    layers.Dense(64, activation='linear', input_shape=(dset_features.shape[1],)),  # Hidden layer 1
    layers.Dense(32, activation='selu'),  # Hidden layer 2
    layers.Dense(1, activation='linear')  # Output layer
])


dset_model_MultiLayerPerceptron.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

Training

In [6]:
dset_model_MultiLayerPerceptron.fit(dset_features, dset_labels, epochs=30,validation_split=0.2)

Epoch 1/30
500/500 [==============================] - 1s 1ms/step - loss: 3308842.7500 - accuracy: 6.2500e-05 - val_loss: 2.0859 - val_accuracy: 0.0000e+00
Epoch 2/30
500/500 [==============================] - 1s 1ms/step - loss: 2.5664 - accuracy: 6.2500e-05 - val_loss: 8.6860 - val_accuracy: 0.0000e+00
Epoch 3/30
500/500 [==============================] - 0s 986us/step - loss: 3.7069 - accuracy: 6.2500e-05 - val_loss: 144.6802 - val_accuracy: 0.0000e+00
Epoch 4/30
500/500 [==============================] - 0s 989us/step - loss: 5.9788 - accuracy: 6.2500e-05 - val_loss: 0.0819 - val_accuracy: 0.0000e+00
Epoch 5/30
500/500 [==============================] - 1s 1ms/step - loss: 9.8713 - accuracy: 6.2500e-05 - val_loss: 3.0062 - val_accuracy: 0.0000e+00
Epoch 6/30
500/500 [==============================] - 0s 998us/step - loss: 5.0899 - accuracy: 6.2500e-05 - val_loss: 0.2281 - val_accuracy: 0.0000e+00
Epoch 7/30
500/500 [==============================] - 1s 1ms/step - loss: 7.5880 - acc

Testing

In [7]:
dset_model_MultiLayerPerceptron.predict(dset_features[:20])

1/1 [==============================] - 0s 35ms/step


array([[ 1.0379713],
       [ 3.0287118],
       [ 5.034981 ],
       [ 7.006753 ],
       [ 9.006344 ],
       [10.987668 ],
       [12.993192 ],
       [15.011741 ],
       [17.036127 ],
       [19.060934 ],
       [21.083021 ],
       [23.100744 ],
       [25.112593 ],
       [27.118288 ],
       [29.118704 ],
       [31.087624 ],
       [33.05057  ],
       [35.021183 ],
       [36.99822  ],
       [38.98062  ]], dtype=float32)

Convolutional Neural Network

Designing

In [24]:
dset_model_Convolutional = tf.keras.Sequential([
    layers.Conv1D(32, kernel_size=2, activation='relu', input_shape=(2, 1)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='linear')
])
dset_model_Convolutional.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


Training

In [25]:
dset_model_Convolutional.fit(dset_features, dset_labels, epochs=20, validation_split=0.2)

Epoch 1/20
500/500 [==============================] - 1s 1ms/step - loss: 24814824.0000 - mae: 1715.2192 - val_loss: 0.5929 - val_mae: 0.7627
Epoch 2/20
500/500 [==============================] - 1s 1ms/step - loss: 0.2156 - mae: 0.3858 - val_loss: 0.4383 - val_mae: 0.6546
Epoch 3/20
500/500 [==============================] - 0s 989us/step - loss: 1.4276 - mae: 0.4854 - val_loss: 0.3698 - val_mae: 0.6005
Epoch 4/20
500/500 [==============================] - 1s 1ms/step - loss: 0.2012 - mae: 0.3739 - val_loss: 0.4241 - val_mae: 0.6437
Epoch 5/20
500/500 [==============================] - 1s 1ms/step - loss: 1.4499 - mae: 0.4937 - val_loss: 0.3731 - val_mae: 0.6033
Epoch 6/20
500/500 [==============================] - 1s 1ms/step - loss: 0.1999 - mae: 0.3725 - val_loss: 0.5468 - val_mae: 0.7321
Epoch 7/20
500/500 [==============================] - 1s 1ms/step - loss: 0.1992 - mae: 0.3719 - val_loss: 0.4088 - val_mae: 0.6319
Epoch 8/20
500/500 [==============================] - 1s 1ms/ste

Testing

In [26]:
dset_model_Convolutional.predict(dset_features[:20])

1/1 [==============================] - 0s 37ms/step


array([[ 0.28406343],
       [ 2.4249287 ],
       [ 4.6652017 ],
       [ 6.900585  ],
       [ 9.061536  ],
       [11.135099  ],
       [13.20866   ],
       [15.282221  ],
       [17.344887  ],
       [19.399569  ],
       [21.435888  ],
       [23.472208  ],
       [25.508528  ],
       [27.539839  ],
       [29.569094  ],
       [31.597746  ],
       [33.611156  ],
       [35.62041   ],
       [37.62036   ],
       [39.620316  ]], dtype=float32)

LSTM

Designing

In [27]:
dset_model_LSTM = tf.keras.Sequential([
    layers.LSTM(32, activation='relu', input_shape=(2, 1)),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='linear')  # Output layer with linear activation for regression
])

# Compile the model with Mean Squared Error loss
dset_model_LSTM.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])  # Use mean absolute error (mae) as a metric if needed


Training

In [28]:
dset_model_LSTM.fit(dset_features, dset_labels, epochs=50, validation_split=0.2)


Epoch 1/50
500/500 [==============================] - 1s 2ms/step - loss: 58669876.0000 - mae: 3137.0920 - val_loss: 1.4783 - val_mae: 1.2015
Epoch 2/50
500/500 [==============================] - 1s 1ms/step - loss: 1.1439 - mae: 0.7844 - val_loss: 0.8257 - val_mae: 0.8934
Epoch 3/50
500/500 [==============================] - 1s 1ms/step - loss: 0.9094 - mae: 0.7411 - val_loss: 0.9715 - val_mae: 0.9708
Epoch 4/50
500/500 [==============================] - 1s 1ms/step - loss: 0.7923 - mae: 0.7182 - val_loss: 2.3514 - val_mae: 1.5196
Epoch 5/50
500/500 [==============================] - 1s 1ms/step - loss: 0.7440 - mae: 0.7008 - val_loss: 0.8118 - val_mae: 0.8859
Epoch 6/50
500/500 [==============================] - 1s 1ms/step - loss: 0.7388 - mae: 0.7007 - val_loss: 1.6528 - val_mae: 1.2718
Epoch 7/50
500/500 [==============================] - 1s 1ms/step - loss: 0.6339 - mae: 0.6659 - val_loss: 3.2110 - val_mae: 1.7783
Epoch 8/50
500/500 [==============================] - 1s 1ms/step 

Testing

In [29]:
dset_model_LSTM.predict(dset_features[:20])

1/1 [==============================] - 0s 90ms/step


array([[ 1.0587265],
       [ 3.0541456],
       [ 5.080892 ],
       [ 6.977174 ],
       [ 8.973065 ],
       [10.988362 ],
       [13.004357 ],
       [15.015603 ],
       [17.020046 ],
       [19.017853 ],
       [21.010542 ],
       [23.000183 ],
       [24.988811 ],
       [26.978113 ],
       [28.969303 ],
       [30.963125 ],
       [32.957077 ],
       [34.95242  ],
       [36.94988  ],
       [38.949604 ]], dtype=float32)

 
.



























 .

TestOuts

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load the dataset
d_set = pd.read_csv('./../Data/addition_dataset.csv')
dset_features = d_set['equation'].values
dset_labels = d_set['result'].values

# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(dset_features)
word_index = tokenizer.word_index

# Convert text to sequences and pad them
sequences = tokenizer.texts_to_sequences(dset_features)
padded_sequences = pad_sequences(sequences)

# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(word_index) + 1, output_dim=16, input_length=padded_sequences.shape[1]),
    #tf.keras.layers.Flatten(),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Convert labels to NumPy array
dset_labels = tf.convert_to_tensor(dset_labels, dtype=tf.float32)

# Train the model
model.fit(padded_sequences, dset_labels, epochs=200,validation_split=0.2)

# Test the model with new data
test_texts = ["23+24", "27+28"]
test_sequences = tokenizer.texts_to_sequences(test_texts)
padded_test_sequences = pad_sequences(test_sequences, maxlen=padded_sequences.shape[1])
predictions = model.predict(padded_test_sequences)

# Print the predictions
for text, prediction in zip(test_texts, predictions):
    print(f"Text: {text}, Prediction: {prediction[0]}")


In [ ]:

model.predict(pad_sequences(tokenizer.texts_to_sequences("123+1"), maxlen=padded_sequences.shape[1]))